name: Publish dev
on:
  push:
    branches:
      - maina
      - deva
  create:
    tags:
      - 'v\d\.\d\.\d-(dev|rc)\d'

jobs:
  publish:
#    if: (github.ref == 'refs/heads/dev')
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print github.ref
        run: |
          echo "Current github.ref: ${{ github.ref }}"
          echo "Current github.event: ${{ github.event.ref }}"
          echo "ahha: $GITHUB_REF"
          export
          tag=${{  github.ref_name }}
          branch=$(git branch --contains=$tag |\
          	head -n1 |\
          	cut -c3-)
          echo $branch
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true