name: Publish
on:
  create:
    tags:
      - 'v\d\.\d\.\d'
      - 'v\d\.\d\.\d-(dev|rc)\d'

jobs:
  publish:
#    if: >
#          (github.ref == 'refs/heads/main' && contains(github.event.ref, 'refs/tags/v\d\.\d\.\d')) ||
#          (github.ref == 'refs/heads/dev' && contains(github.event.ref, 'refs/tags/v\d\.\d\.\d-(dev|rc)\d'))
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Print github.ref
        run: |
          echo "Current github.ref: ${{ github.ref }}"
          echo "Current github.event: ${{ github.event.ref }}"
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies
        run: |
          poetry build
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true